### ISSUE TITLE
Running latest code line in local IIS Express results in infinite icon with error message "An unhandled error has occurred. Reload"

### ISSUE THREAD

**Issue by ericwood8** [Jinjinov/TheLastTime#2]
![UnhandledError](https://user-images.githubusercontent.com/2171474/112780955-824e2280-900f-11eb-8cf1-f70438738bdb.png)
Steps I Took: 
1) Pulled down your latest code.  
2) In Visual Studio (VS), I restored NuGet packages at the solution level.  
3) Built application in VS
4) Ran in VS
5) Authorized use of fake certificate for HTTPS for local browser.  

Running latest code line in local IIS Express results in infinite loading with error message "An unhandled error has occurred. Reload".  What is the best way to debug this?  The "Output" window of in VS does not show an error.

**Comment by Jinjinov** [comment]
To debug "An unhandled error has occurred. Reload" always use Developer tools in Google Chrome or Microsoft Edge (press F12 to open tools).

In Developer tools open the `Application` tab and select `Storage`. Click on `Clear site data` and then right-click on the reload button in Chrome and choose `Empty Cache and Hard Reload`.

If this doesn't help, open the `Console` tab in the Developer tools. You will see the exception details and the call stack.

I am not familiar with the Developer tools in Firefox, but they should be very similar.
